#go here to scan face
MDScreen:
    name: 'datacollect'

    MDGridLayout: # main layout
        cols: 1

        Image: # Background image
            source: 'Assets/face_scan_complete.png'
            allow_stretch: True
            keep_ratio: False
            size_hint: 1, 1
            on_touch_down:
                root.manager.current = 'mainmenu'
                root.manager.transition.direction = 'left'

